language: node_js

matrix:
    include:
        - env: PROJECT=state-machine
        - env: PROJECT=task-satisfier

cache:
  yarn: true
  directories:
    - node_modules

script: cd $PROJECT && yarn install && yarn test